# Generated by Django 2.1.7 on 2021-07-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0002_auto_20210708_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='vantilator_available',
            new_name='_available',
        ),
    ]
