# Generated by Django 2.1.7 on 2021-07-08 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0003_auto_20210708_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='_available',
            new_name='vantilator_available',
        ),
    ]
