# Generated by Django 2.1.7 on 2021-07-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0005_auto_20210708_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='hospital',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
