# Generated by Django 2.1.7 on 2021-07-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0007_availibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='availibility',
            name='available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='availibility',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
